name: "Simple Paths Filter"
description: "Detect file changes with multiple patterns per filter"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Detect file changes
      shell: bash
      run: |
        bash ${{ github.action_path }}/scripts/detect.sh "${{ inputs.base_ref }}" "${{ inputs.filters }}"
      env:
        GITHUB_OUTPUT: $GITHUB_OUTPUT

inputs:
  base_ref:
    description: 'The base branch to compare changes against'
    required: false
    default: 'origin/main'
  filters:
    description: |
      YAML-style multiline filters. Example:
        relevant_files_changed:
          - metadata/**
          - tests/src/**
    required: true
